spring:
  application:
    name: flagd-hub-api
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
#    allow-bean-definition-overriding: true # Allow overriding bean definitions (optional)

debug: true

security:
  basic:
    enabled: ${IS_SECURED:false}

cors:
  allowed:
    origins: http://localhost:3000

server:
  port: 8090 # Port the application will run on
  insecure:
    port: 8091 # Insecure port for internal endpoints

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all Actuator endpoints
      base-path: /actuator # Base path for Actuator endpoints
  health:
    defaults:
      enabled: true # Enable default health checks

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.flagd.hub: DEBUG

actuator:
  metrics:
    export:
      prometheus:
        enabled: true # Example for exporting metrics to Prometheus
